name: Pull Request

on:
    pull_request:
        branches: [ develop ]

jobs:
    pipeline:

        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Danger
                uses: danger/kotlin@1.0.0-beta.3
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            -   name: Set up environment
                uses: actions/setup-java@v1
                with:
                    java-version: 1.8

            -   name: Change wrapper permissions
                run: chmod +x ./gradlew

            -   name: detekt
                run: ./gradlew detekt

            -   name: Unit testing
                run: ./gradlew testReleaseUnitTest
