name: Pull Request

on:
    pull_request:
        branches: [ develop ]

jobs:
    pipeline:

        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Set up environment
                uses: actions/setup-java@v1
                with:
                    java-version: 1.8

            -   name: Change wrapper permissions
                run: chmod +x ./gradlew

            -   name: ktlint
                run: ./gradlew ktlintReleaseCheck
